# Conexão com o Banco Virtual do Aiven
spring.datasource.url=jdbc:mysql://unipark-unipark.d.aivencloud.com:25049/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin

spring.datasource.password=AVNS_qcNyXQFHcsoLQIiLntF

# Configurações do Hibernate (Criação automática das tabelas)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect